server:
  port: 9090
  servlet:
    context-path: /ingestion

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ingestion
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  profiles:
    active:

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB